import Link from "next/link";
import type { Metadata } from "next";
import { ArrowRight, BadgeCheck, HeartHandshake, MapPin, ShieldCheck, UsersRound } from "lucide-react";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = {
  title: "About CG Job Care | Jobs & Facility Services in Raipur",
  description: "Learn how CG Job Care supports job seekers, employers, families and businesses with recruitment and facility services across Chhattisgarh.",
  alternates: { canonical: "/about" },
};

const values = [{ icon: BadgeCheck, title: "Clear process", text: "Requirements and candidate profiles are reviewed before the next step." }, { icon: ShieldCheck, title: "Trusted support", text: "Documentation and verification support for roles where it matters." }, { icon: HeartHandshake, title: "Human help", text: "A local team for candidates, employers and facility customers." }];

export default function AboutPage() {
  return <main className="min-h-screen bg-[#F5FAF7] text-[#1E2B26]"><SiteHeader /><section className="bg-[#EEF5F0]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-8 lg:py-16 lg:grid-cols-[1fr_.8fr] lg:px-8 lg:py-20"><div><p className="section-kicker text-[#0F5C38]">LOCAL PEOPLE. PRACTICAL SUPPORT.</p><h1 className="section-title">More than a job listing service.</h1><p className="mt-6 max-w-xl leading-8 text-[#4B5A52]">CG Job Care &amp; Facility Services helps Chhattisgarh connect reliable people with real work. We support candidates finding their next opportunity, employers building teams, and homes or businesses that need trusted services.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/jobs" className="inline-flex items-center gap-2 rounded-lg bg-[#157A4A] px-5 py-3 text-sm font-bold text-white">Explore jobs <ArrowRight size={16} /></Link><Link href="/employer/requirement" className="rounded-lg border border-[#B9D6C6] px-5 py-3 text-sm font-bold text-[#0F5C38]">Hire staff</Link></div></div><div className="rounded-lg bg-[#1E2B26] p-7 text-white shadow-[0_18px_40px_rgba(36,26,20,0.16)]"><MapPin size={25} className="text-[#D4B04A]" /><p className="mt-8 text-sm font-bold tracking-[0.13em] text-[#D4B04A]">ROOTED IN RAIPUR</p><h2 className="mt-3 text-3xl font-black leading-tight">Built for the way local recruitment really works.</h2><p className="mt-4 text-sm leading-7 text-[#DCE8E1]">We know that a job match involves more than a vacancy. It needs clear communication, right documents and reliable follow-up.</p></div></div></section><section className="mx-auto max-w-6xl px-5 py-10 lg:py-20 lg:px-8"><p className="section-kicker text-[#0F5C38]">WHAT WE CARE ABOUT</p><div className="mt-7 grid gap-4 md:grid-cols-3">{values.map((value) => { const Icon = value.icon; return <article key={value.title} className="rounded-lg border border-[#DCE8E1] bg-white p-6"><span className="grid h-11 w-11 place-items-center rounded-lg bg-[#E9F3ED] text-[#157A4A]"><Icon size={21} /></span><h2 className="mt-6 text-xl font-extrabold">{value.title}</h2><p className="mt-3 text-sm leading-6 text-[#4B5A52]">{value.text}</p></article>; })}</div></section><section className="mx-auto mb-16 max-w-6xl rounded-lg border border-[#DCE8E1] bg-white px-6 py-8 sm:px-9"><div className="flex flex-wrap items-center justify-between gap-6"><div><p className="section-kicker text-[#0F5C38]">ONE TEAM, MANY NEEDS</p><h2 className="mt-2 text-2xl font-black">Jobs, security, care and facility support.</h2></div><div className="flex items-center gap-2 text-sm font-bold text-[#4B5A52]"><UsersRound size={19} className="text-[#157A4A]" /> Candidate and client focused</div></div></section></main>;
}
