"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { LockKeyhole } from "lucide-react";

export default function CandidateLoginPage() {
  const router = useRouter(); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(undefined); const values = new FormData(event.currentTarget); const response = await fetch("/api/auth/candidate-login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mobile: values.get("mobile"), password: values.get("password") }) }); const result = await response.json() as { error?: string }; setLoading(false); if (!response.ok) { setError(result.error ?? "Could not sign in."); return; } router.replace("/candidate/dashboard"); router.refresh(); }
  return <main className="grid min-h-screen place-items-center bg-[#F5FAF7] p-5"><section className="w-full max-w-md rounded-lg border border-[#D5E3DB] bg-white p-7 shadow-[0_16px_45px_rgba(130,76,40,.10)]"><Link href="/" className="text-sm font-bold text-[#0F5C38]">Back to CG Job Care</Link><span className="mt-8 grid h-12 w-12 place-items-center rounded-lg bg-[#E9F3ED] text-[#157A4A]"><LockKeyhole size={22} /></span><p className="section-kicker mt-7 text-[#0F5C38]">CANDIDATE LOGIN</p><h1 className="mt-2 text-3xl font-black text-[#1E2B26]">Welcome back.</h1><p className="mt-3 text-sm leading-6 text-[#4B5A52]">Check applications, interviews and profile progress from one simple dashboard.</p><form onSubmit={submit} className="mt-7 grid gap-4"><label className="grid gap-2 text-sm font-bold">Mobile number<input name="mobile" inputMode="numeric" pattern="[0-9]{10}" required className="h-12 rounded-md border border-[#D5E3DB] px-3 outline-none focus:border-[#157A4A]" /></label><label className="grid gap-2 text-sm font-bold">Password<input name="password" type="password" required className="h-12 rounded-md border border-[#D5E3DB] px-3 outline-none focus:border-[#157A4A]" /></label><button disabled={loading} className="rounded-lg bg-[#157A4A] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{loading ? "Signing in..." : "Sign in"}</button>{error && <p className="rounded-md bg-[#E9F3ED] px-3 py-2 text-sm font-bold text-[#0F5C38]">{error}</p>}</form><p className="mt-6 text-sm text-[#4B5A52]">New candidate? <Link href="/candidate/register" className="font-bold text-[#0F5C38]">Create your profile</Link></p></section></main>;
}