"use client";

import { useEffect, useState } from "react";
import { Bell, BriefcaseBusiness, Building2, CheckCircle2, ChevronDown, FileText, LayoutDashboard, Megaphone, Plus, Send, Settings, UsersRound } from "lucide-react";
import type { Job, JobStatus } from "@/lib/portal";

type DashboardData = { metrics: { activeJobs: number; candidates: number; applications: number; newRequirements: number; serviceRequests: number }; jobs: Job[]; announcements: Array<{ id: string; title: string; active: boolean }>; websitePosts: Array<{ id: string; title: string; category: string; published: boolean }>; notifications: Array<{ id: string; title: string; audience: string; channel: string }>; employerRequirements: Array<{ id: string; company: string; jobTitle: string; candidatesRequired: number; city: string; status: string }>; serviceRequests: Array<{ id: string; customerName: string; serviceType: string; city: string; status: string }> };
type Tab = "overview" | "jobs" | "content" | "notifications" | "leads";

const statuses: JobStatus[] = ["PUBLISHED", "PAUSED", "CLOSED", "DRAFT"];

export function AdminWorkspace() {
  const [data, setData] = useState<DashboardData>();
  const [tab, setTab] = useState<Tab>("overview");
  const [message, setMessage] = useState<string>();
  const [loading, setLoading] = useState(true);

  async function refresh() { const result = await fetch("/api/admin/dashboard").then((response) => response.json()) as { data: DashboardData }; setData(result.data); setLoading(false); }
  useEffect(() => { refresh(); }, []);

  async function submitContent(form: HTMLFormElement) {
    const values = Object.fromEntries(new FormData(form).entries());
    const response = await fetch("/api/admin/content", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) });
    const result = await response.json() as { error?: string };
    if (!response.ok) { setMessage(result.error ?? "Could not save content."); return; }
    setMessage("Saved successfully."); form.reset(); refresh();
  }

  async function updateStatus(jobId: string, status: JobStatus) { await fetch(`/api/admin/jobs/${jobId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); setMessage("Job status updated."); refresh(); }
  const nav = [{ id: "overview" as Tab, label: "Overview", icon: LayoutDashboard }, { id: "jobs" as Tab, label: "Jobs", icon: BriefcaseBusiness }, { id: "content" as Tab, label: "Website content", icon: FileText }, { id: "notifications" as Tab, label: "Notifications", icon: Bell }, { id: "leads" as Tab, label: "Leads & requests", icon: UsersRound }];
  const metrics = data ? [{ label: "Active jobs", value: data.metrics.activeJobs, color: "bg-[#e8f5ed] text-[#258653]", icon: BriefcaseBusiness }, { label: "Candidates", value: data.metrics.candidates, color: "bg-[#eaf1ff] text-[#3d69be]", icon: UsersRound }, { label: "New requirements", value: data.metrics.newRequirements, color: "bg-[#fff0e6] text-[#d46124]", icon: Building2 }, { label: "Service leads", value: data.metrics.serviceRequests, color: "bg-[#f6ecff] text-[#7f4bb0]", icon: Megaphone }] : [];

  return <div className="min-h-screen bg-[#f5f7f5] text-[#25372e]"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-[#dfe8e1] bg-white p-5 lg:block"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-[#e95d2b] text-sm font-black text-white">CG</span><div><strong className="block">CG Job Care</strong><span className="text-xs text-[#7a8d82]">Admin workspace</span></div></div><nav className="mt-10 grid gap-1">{nav.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={`flex items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-bold ${tab === item.id ? "bg-[#fff0e7] text-[#c9471e]" : "text-[#65786d] hover:bg-[#f3f7f4]"}`}><Icon size={18} />{item.label}</button>; })}</nav><div className="absolute bottom-5 left-5 right-5 rounded-lg bg-[#35231c] p-4 text-white"><Settings size={18} className="text-[#ffcf68]" /><p className="mt-3 text-sm font-bold">Admin controls</p><p className="mt-1 text-xs leading-5 text-[#dfcfc6]">Manage public website content and operations.</p></div></aside><main className="lg:pl-64"><header className="flex min-h-[78px] items-center justify-between border-b border-[#dfe8e1] bg-white px-5 lg:px-9"><div><p className="text-xs font-bold tracking-[0.1em] text-[#e95d2b]">ADMIN PORTAL</p><h1 className="mt-1 text-xl font-black">{nav.find((item) => item.id === tab)?.label}</h1></div><div className="flex items-center gap-3"><button className="grid h-10 w-10 place-items-center rounded-lg border border-[#e0e8e2] text-[#63766b]" aria-label="Notifications"><Bell size={18} /></button><span className="grid h-10 w-10 place-items-center rounded-full bg-[#e8f5ed] text-sm font-black text-[#258653]">A</span></div></header><div className="px-5 py-7 lg:px-9">{message && <div className="mb-5 flex items-center justify-between rounded-lg bg-[#e8f5ed] px-4 py-3 text-sm font-bold text-[#258653]"><span>{message}</span><button onClick={() => setMessage(undefined)}>x</button></div>}{loading || !data ? <p className="text-sm font-semibold text-[#71837a]">Loading dashboard...</p> : <>{tab === "overview" && <Overview metrics={metrics} data={data} setTab={setTab} />}{tab === "jobs" && <JobsTab jobs={data.jobs} updateStatus={updateStatus} />}{tab === "content" && <ContentTab submitContent={submitContent} data={data} />}{tab === "notifications" && <NotificationsTab submitContent={submitContent} data={data} />}{tab === "leads" && <LeadsTab data={data} />}</>}</div></main></div>;
}

function Overview({ metrics, data, setTab }: { metrics: Array<{ label: string; value: number; color: string; icon: typeof BriefcaseBusiness }>; data: DashboardData; setTab: (tab: Tab) => void }) { return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => { const Icon = metric.icon; return <article key={metric.label} className="rounded-lg border border-[#e0e8e2] bg-white p-5"><span className={`grid h-10 w-10 place-items-center rounded-lg ${metric.color}`}><Icon size={19} /></span><p className="mt-5 text-3xl font-black">{metric.value}</p><p className="mt-1 text-sm font-semibold text-[#71837a]">{metric.label}</p></article>; })}</div><div className="mt-7 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-lg border border-[#e0e8e2] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.1em] text-[#e95d2b]">ACTION QUEUE</p><h2 className="mt-1 text-lg font-black">Needs your attention</h2></div><button onClick={() => setTab("leads")} className="text-sm font-bold text-[#c9471e]">View all</button></div><div className="mt-5 grid gap-3"><QueueItem title={`${data.metrics.newRequirements} new manpower requirements`} note="Review and approve before creating public jobs" /><QueueItem title={`${data.metrics.serviceRequests} new facility service requests`} note="Assign follow-up or update customer" /><QueueItem title={`${data.jobs.filter((job) => job.status === "PUBLISHED").length} jobs currently published`} note="Review visibility and expiry dates" /></div></section><section className="rounded-lg bg-[#35231c] p-6 text-white"><Megaphone size={22} className="text-[#ffcf68]" /><h2 className="mt-5 text-xl font-black">Keep your website current.</h2><p className="mt-2 text-sm leading-6 text-[#ecd9cf]">Add an urgent hiring notice, publish an update or send a notification to candidates.</p><button onClick={() => setTab("content")} className="mt-5 rounded-lg bg-[#e95d2b] px-4 py-2.5 text-sm font-bold">Manage content</button></section></div></> }
function QueueItem({ title, note }: { title: string; note: string }) { return <div className="flex items-start gap-3 rounded-lg bg-[#f7faf8] p-4"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-[#e95d2b]" /><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-[#71837a]">{note}</p></div></div>; }
function JobsTab({ jobs, updateStatus }: { jobs: Job[]; updateStatus: (jobId: string, status: JobStatus) => void }) { return <section className="rounded-lg border border-[#e0e8e2] bg-white"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#e7eee9] px-6 py-5"><div><p className="text-xs font-bold tracking-[.1em] text-[#e95d2b]">RECRUITMENT</p><h2 className="mt-1 text-lg font-black">Job publication control</h2></div><button className="inline-flex items-center gap-2 rounded-lg bg-[#e95d2b] px-4 py-2.5 text-sm font-bold text-white"><Plus size={16} /> Add job</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[#f7faf8] text-xs font-bold text-[#71837a]"><tr><th className="px-6 py-3">JOB</th><th>LOCATION</th><th>VACANCIES</th><th>STATUS</th><th className="px-6">ACTION</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id} className="border-t border-[#edf1ee]"><td className="px-6 py-4"><p className="font-bold">{job.title}</p><p className="mt-1 text-xs text-[#71837a]">{job.company} | {job.id}</p></td><td>{job.city}</td><td>{job.vacancies}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${job.status === "PUBLISHED" ? "bg-[#e8f5ed] text-[#258653]" : "bg-[#fff0e7] text-[#c9471e]"}`}>{job.status}</span></td><td className="px-6"><label className="sr-only" htmlFor={job.id}>Change status</label><select id={job.id} value={job.status} onChange={(event) => updateStatus(job.id, event.target.value as JobStatus)} className="rounded-md border border-[#dce6df] bg-white px-2 py-1.5 text-xs font-bold text-[#52665c]">{statuses.map((status) => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div></section>; }
function ContentTab({ submitContent, data }: { submitContent: (form: HTMLFormElement) => void; data: DashboardData }) { return <div className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><section className="rounded-lg border border-[#e0e8e2] bg-white p-6"><p className="text-xs font-bold tracking-[.1em] text-[#e95d2b]">WEBSITE NOTICE</p><h2 className="mt-1 text-lg font-black">Add announcement</h2><form onSubmit={(event) => { event.preventDefault(); submitContent(event.currentTarget); }} className="mt-5 grid gap-4"><input type="hidden" name="type" value="announcement" /><label className="grid gap-2 text-sm font-bold">Announcement title<input name="title" required className="admin-input" placeholder="Urgent Hiring: 25 Office Assistants" /></label><label className="grid gap-2 text-sm font-bold">Optional link<input name="link" className="admin-input" placeholder="/jobs/JOB-10001" /></label><button className="inline-flex w-fit items-center gap-2 rounded-lg bg-[#e95d2b] px-4 py-2.5 text-sm font-bold text-white"><Plus size={16} /> Publish notice</button></form></section><section className="rounded-lg border border-[#e0e8e2] bg-white p-6"><p className="text-xs font-bold tracking-[.1em] text-[#e95d2b]">CONTENT POSTS</p><h2 className="mt-1 text-lg font-black">Publish website update</h2><form onSubmit={(event) => { event.preventDefault(); submitContent(event.currentTarget); }} className="mt-5 grid gap-4"><input type="hidden" name="type" value="post" /><label className="grid gap-2 text-sm font-bold">Post title<input name="title" required className="admin-input" placeholder="New hiring drive in Raipur" /></label><label className="grid gap-2 text-sm font-bold">Short summary<textarea name="excerpt" required className="admin-input min-h-24 py-3" placeholder="Write a short update for your website." /></label><label className="grid gap-2 text-sm font-bold">Category<select name="category" required className="admin-input"><option value="JOB_TIP">Job tip</option><option value="COMPANY_NEWS">Company news</option><option value="SERVICE_UPDATE">Service update</option></select></label><button className="inline-flex w-fit items-center gap-2 rounded-lg bg-[#35231c] px-4 py-2.5 text-sm font-bold text-white"><FileText size={16} /> Publish post</button></form></section><section className="xl:col-span-2 rounded-lg border border-[#e0e8e2] bg-white p-6"><h2 className="text-lg font-black">Current website content</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{[...data.announcements.map((item) => ({ title: item.title, type: "Announcement" })), ...data.websitePosts.map((item) => ({ title: item.title, type: item.category.replaceAll("_", " ") }))].map((item, index) => <div key={`${item.title}-${index}`} className="rounded-lg bg-[#f7faf8] p-4"><p className="text-xs font-bold text-[#e95d2b]">{item.type}</p><p className="mt-1 text-sm font-bold">{item.title}</p></div>)}</div></section></div>; }
function NotificationsTab({ submitContent, data }: { submitContent: (form: HTMLFormElement) => void; data: DashboardData }) { return <div className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><section className="rounded-lg border border-[#e0e8e2] bg-white p-6"><p className="text-xs font-bold tracking-[.1em] text-[#e95d2b]">CANDIDATE & EMPLOYER MESSAGES</p><h2 className="mt-1 text-lg font-black">Create notification</h2><form onSubmit={(event) => { event.preventDefault(); submitContent(event.currentTarget); }} className="mt-5 grid gap-4"><input type="hidden" name="type" value="notification" /><label className="grid gap-2 text-sm font-bold">Title<input name="title" required className="admin-input" placeholder="New jobs available in Raipur" /></label><label className="grid gap-2 text-sm font-bold">Message<textarea name="message" required className="admin-input min-h-24 py-3" placeholder="Write the message to send." /></label><div className="grid grid-cols-2 gap-3"><label className="grid gap-2 text-sm font-bold">Audience<select name="audience" className="admin-input"><option value="CANDIDATES">Candidates</option><option value="EMPLOYERS">Employers</option><option value="ALL_USERS">All users</option></select></label><label className="grid gap-2 text-sm font-bold">Channel<select name="channel" className="admin-input"><option value="WEBSITE">Website</option><option value="EMAIL">Email</option><option value="SMS">SMS</option><option value="WHATSAPP">WhatsApp</option></select></label></div><button className="inline-flex w-fit items-center gap-2 rounded-lg bg-[#e95d2b] px-4 py-2.5 text-sm font-bold text-white"><Send size={16} /> Create notification</button></form></section><section className="rounded-lg border border-[#e0e8e2] bg-white p-6"><h2 className="text-lg font-black">Recent notifications</h2><p className="mt-1 text-sm text-[#71837a]">In production, channel adapters will deliver Email, SMS and WhatsApp messages.</p><div className="mt-5 grid gap-3">{data.notifications.length ? data.notifications.map((notification) => <div key={notification.id} className="rounded-lg bg-[#f7faf8] p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-bold">{notification.title}</p><span className="rounded-full bg-[#e8f5ed] px-2 py-1 text-[10px] font-bold text-[#258653]">{notification.channel}</span></div><p className="mt-2 text-xs text-[#71837a]">{notification.audience.replaceAll("_", " ")}</p></div>) : <p className="rounded-lg border border-dashed border-[#dce6df] p-6 text-sm text-[#71837a]">No notifications created yet.</p>}</div></section></div>; }
function LeadsTab({ data }: { data: DashboardData }) { return <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-lg border border-[#e0e8e2] bg-white p-6"><h2 className="text-lg font-black">Employer requirements</h2><div className="mt-5 grid gap-3">{data.employerRequirements.length ? data.employerRequirements.map((lead) => <div key={lead.id} className="rounded-lg bg-[#f7faf8] p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{lead.jobTitle}</p><p className="mt-1 text-sm text-[#71837a]">{lead.company} | {lead.city}</p></div><span className="rounded-full bg-[#fff0e7] px-2 py-1 text-xs font-bold text-[#c9471e]">{lead.status}</span></div><p className="mt-3 text-xs font-bold text-[#52665c]">{lead.candidatesRequired} candidates required</p></div>) : <p className="rounded-lg border border-dashed border-[#dce6df] p-6 text-sm text-[#71837a]">No employer requirements yet.</p>}</div></section><section className="rounded-lg border border-[#e0e8e2] bg-white p-6"><h2 className="text-lg font-black">Facility service requests</h2><div className="mt-5 grid gap-3">{data.serviceRequests.length ? data.serviceRequests.map((lead) => <div key={lead.id} className="rounded-lg bg-[#f7faf8] p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{lead.serviceType.replaceAll("_", " ")}</p><p className="mt-1 text-sm text-[#71837a]">{lead.customerName} | {lead.city}</p></div><span className="rounded-full bg-[#fff0e7] px-2 py-1 text-xs font-bold text-[#c9471e]">{lead.status}</span></div></div>) : <p className="rounded-lg border border-dashed border-[#dce6df] p-6 text-sm text-[#71837a]">No service requests yet.</p>}</div></section></div>; }