import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { portalStore } from "@/lib/portal";

export const metadata: Metadata = { title: "Privacy Policy | CG Job Care", description: "How CG Job Care collects, uses, protects and deletes candidate and customer information.", alternates: { canonical: "/privacy" } };

export default async function PrivacyPolicyPage() {
  const settings = await portalStore.getSiteSettings();
  return <main className="min-h-screen bg-[#F5FAF7] text-[#1E2B26]"><SiteHeader /><article className="mx-auto max-w-4xl px-5 py-12"><p className="section-kicker text-[#157A4A]">LEGAL & PRIVACY</p><h1 className="mt-2 text-4xl font-black">Privacy Policy</h1><p className="mt-3 text-sm text-[#6B7A72]">Effective and last updated: 21 September 2026</p><div className="mt-8 grid gap-5">
    <PolicySection title="1. Who we are"><p>{settings.companyName} provides recruitment coordination, job application support and facility-service enquiry management in Chhattisgarh. Questions about this policy can be submitted through our <Link className="font-bold text-[#0F5C38] underline" href="/contact">contact page</Link>{settings.email ? <> or emailed to <a className="font-bold text-[#0F5C38] underline" href={`mailto:${settings.email}`}>{settings.email}</a></> : null}{settings.phone ? <>. You may also call <a className="font-bold text-[#0F5C38] underline" href={`tel:${settings.phone}`}>{settings.phone}</a></> : null}.</p></PolicySection>
    <PolicySection title="2. Information we collect"><p>Candidate account details may include name, mobile number, email, location, address, education, experience, job preference and application activity. When voluntarily uploaded, documents may include a resume, photograph, Aadhaar, PAN, qualification, experience or police-verification records. Employer and service forms collect contact and requirement details.</p></PolicySection>
    <PolicySection title="3. Why we use information"><p>We use information to create and secure accounts, match candidates with suitable jobs, process applications, coordinate interviews, verify documents, respond to service requests, prevent misuse and maintain operational records. We do not use identity documents for unrelated advertising.</p></PolicySection>
    <PolicySection title="4. Candidate documents"><p>Candidate documents are optional unless a specific job or verification stage requires them. They are stored as authenticated private assets. Access is limited to the candidate and authorized administrators through short-lived signed links, and document access is logged. Candidates can replace or delete individual documents from their profile.</p></PolicySection>
    <PolicySection title="5. Sharing"><p>Relevant profile or application information may be shared with an employer or service partner when required for a candidate’s application, interview, verification or placement. Infrastructure providers such as hosting, database and media-storage services process data only to operate the platform. We may disclose information where legally required.</p></PolicySection>
    <PolicySection title="6. Retention"><p>Active account information is retained while recruitment or placement support is being provided. Candidate accounts and documents are scheduled for a retention review after 24 months and may be retained longer when the account remains active, an application is ongoing, fraud prevention is required or law requires a record. Completed deletion requests remove the candidate profile and private documents; limited transaction records may remain without an accessible candidate profile where required for legitimate records.</p></PolicySection>
    <PolicySection title="7. Your choices and rights"><p>Candidates can review and update their profile, download a structured copy of their information, delete individual documents, withdraw from document processing by deleting documents, and submit or cancel an account deletion request from the Privacy & Data section. Requests may require identity verification before completion.</p></PolicySection>
    <PolicySection title="8. Security"><p>We use password hashing, signed sessions, role-based access, private document delivery, file type and size restrictions, database access controls and audit logs. No online service can promise absolute security; suspected misuse should be reported promptly using the contact details above.</p></PolicySection>
    <PolicySection title="9. Age requirement"><p>Candidate accounts are intended for people aged 18 years or older. Please contact us instead of registering if you are under 18.</p></PolicySection>
    <PolicySection title="10. Updates"><p>Material policy changes will be reflected by a new effective date and, where appropriate, an in-product notice or renewed consent.</p></PolicySection>
  </div><div className="mt-8 flex flex-wrap gap-4 text-sm font-bold"><Link href="/terms" className="text-[#0F5C38] underline">Terms and Conditions</Link><Link href="/candidate/privacy" className="text-[#0F5C38] underline">Candidate Privacy Centre</Link><Link href="/" className="text-[#0F5C38] underline">Back to home</Link></div></article></main>;
}

function PolicySection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-[#DCE8E1] bg-white p-6"><h2 className="text-lg font-black">{title}</h2><div className="mt-3 text-sm leading-7 text-[#4B5A52]">{children}</div></section>; }
